### ISSUE TITLE
Create comment model

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/team1-hackathon-april-2023#23]
## Tasks
- [ ] add owner field (foreign key to user)
- [ ] add post field (foreign key to post)
- [ ] add create at field (datetime field)
- [ ] add content field (text field)
