### ISSUE TITLE
AllAuth set up

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/team1-hackathon-april-2023#26]
## Tasks
- [ ] Install the django allauth package and add to requirements.txt.
- [ ] Add allauth URL to urls.py.
- [ ] In settings.py, update installed apps, add site_id and add redirect locations for login and logout.
- [ ] Migrate the changes.
